{"$ref": "https://www.cert.ssi.gouv.fr/openapi.json", "affected_systems": [{"description": "CPython sans le dernier correctif de s\u00e9curit\u00e9", "product": {"name": "CPython", "vendor": {"name": "Python", "scada": false}}}], "affected_systems_content": "", "content": "## Solutions\n\nSe r\u00e9f\u00e9rer au bulletin de s\u00e9curit\u00e9 de l'\u00e9diteur pour l'obtention des correctifs (cf. section Documentation).", "cves": [{"name": "CVE-2025-4516", "url": "https://www.cve.org/CVERecord?id=CVE-2025-4516"}], "links": [], "reference": "CERTFR-2025-AVI-0415", "revisions": [{"description": "Version initiale", "revision_date": "2025-05-16T00:00:00.000000"}], "risks": [{"description": "D\u00e9ni de service"}], "summary": "Une vuln\u00e9rabilit\u00e9 a \u00e9t\u00e9 d\u00e9couverte dans Python. Elle permet \u00e0 un attaquant de provoquer un d\u00e9ni de service.", "title": "Vuln\u00e9rabilit\u00e9 dans Python", "vendor_advisories": [{"published_at": "2025-05-15", "title": "Bulletin de s\u00e9curit\u00e9 Python L75IPBBTSCYEF56I2M4KIW353BB3AY74", "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/"}]}